spring:
  task:
    scheduling:
      pool:
        size: 10
      thread-name-prefix: datech-schedul
    execution:
      shutdown:
        #        线程关闭时是否等所有任务结束
        await-termination: false
        #        线程最大的等待时间，防止线程陷入循环关不掉
        await-termination-period: 10s
  shardingsphere:
    datasource:
      master:
        type: com.zaxxer.hikari.HikariDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        jdbcUrl: jdbc:mysql://localhost:13306/datech_zjfh?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
        username: root
        password: 123456
      slave0:
        type: com.zaxxer.hikari.HikariDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        jdbcUrl: jdbc:mysql://127.0.0.1:13307/datech_zjfh?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
        username: root
        password: 123456
      names: master,slave0
    props:
      sql.show: true
    masterslave:
      load-balance-algorithm-type: round_robin
    sharding:
      master-slave-rules:
        master:
          master-data-source-name: master
          slave-data-source-names: slave0
  redis:
    password: 123456
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
      timeout: 10000
      database: 0
    sentinel:
      master: mymaster
      nodes: 127.0.0.1:26379, 127.0.0.1:26380, 127.0.0.1:26381

server:
  port: 9026
  ssl:
    key-alias: datech
    key-store-password: datech123
    key-store-type: PKCS12
    key-store: classpath:datech.p12

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml #扫描mapper下的所有xml文件
  type-aliases-package: com.datech.zjfh.alarm.entity   #扫描实体类包/配置别名
  configuration:
    # 是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
    map-underscore-to-camel-case: true
    # 如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
    call-setters-on-nulls: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


mqtt:
  host: tcp://192.168.2.113:1883
  userName: admin
  passWord: datarnd123
  qos: 0
  clientId: datarnd_1 #ClientId_local必须唯一 比如你已经定了叫ABC  那你就一直叫ABC  其他地方就不要使用ABC了
  timeout: 10
  keepalive: 20
  topic1: /mec/22080109/platform/command  #符号是代表整个warn下面的全部子主题 没有理解的话 可以百度仔细理解一下

  
#ivs1800:
#  url: https://192.168.2.111:18531
#  username: datarnd
#  password: Datarnd@234






